name: tablexplore
version: '0.3.0-23-g7622d8b'
#version-script: git describe --abbrev=1 --tags
summary: data plotting and analysis package
description: |
  Tablexplore is an open source desktop application for data analysis and plotting
  intended for use in both research and education. The program allows quick
  visualization of data, table manipulation tools and supports large data tables.

base: core18
grade: stable
confinement: strict
icon: img/logo.svg

apps:
  tablexplore:
    command: desktop-launch $SNAP/bin/tablexplore
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - network-control
      - mount-observe

parts:
  tablexplore:
    plugin: python
    source: .
    stage-packages:
        - xsel
        - python3-pyqt5
        - libgeos-3.6.2
